const $ = selector => document.querySelector(selector); const money = n => `฿${n.toLocaleString('th-TH')}`; let dashboard;
function headers(){return {'Content-Type':'application/json','X-Admin-Key':$('#key').value};}
async function api(url, options={}) { const response=await fetch(url,{...options,headers:{...headers(),...(options.headers||{})}}); const data=await response.json();if(!response.ok)throw new Error(data.error);return data; }
function render() { const {summary,orders,settings}=dashboard; $('#dashboard').hidden=false; $('#summary').innerHTML=`<div><strong>${summary.orders}</strong><span>ออเดอร์ทั้งหมด</span></div><div><strong>${summary.active_orders}</strong><span>กำลังดำเนินการ</span></div><div><strong>${money(summary.revenue)}</strong><span>ยอดจอง</span></div><div><strong>${summary.ready}</strong><span>พร้อมรับ</span></div>`; $('#slot-capacity').value=settings.slot_capacity; $('#advance-days').value=settings.advance_days; $('#menu-list').innerHTML=settings.menu.map(item=>`<article class="menu-item"><div><h4>${item.name} ${item.available?'':'(ปิดขาย)'}</h4><p>${item.description}</p><p class="price">${money(item.price)}</p></div><button class="text-button" data-menu="${item.id}" data-available="${!item.available}">${item.available?'ปิดขาย':'เปิดขาย'}</button></article>`).join(''); $('#orders').innerHTML=orders.length?orders.map(order=>`<article class="menu-item"><div><h4>${order.id} · ${order.customer.name}</h4><p>${order.customer.phone} · ${order.pickup.date} ${order.pickup.slot}</p><p>${order.items.map(item=>`${item.name} × ${item.quantity}`).join(', ')} · ชำระ: ${order.payment.status}</p><p class="price">${money(order.total)}</p></div><div><select data-order="${order.id}" data-field="status">${['new','confirmed','ready','completed','cancelled'].map(value=>`<option value="${value}" ${value===order.status?'selected':''}>${value}</option>`).join('')}</select><select data-order="${order.id}" data-field="payment_status">${['pending','paid','refunded'].map(value=>`<option value="${value}" ${value===order.payment.status?'selected':''}>${value}</option>`).join('')}</select></div></article>`).join(''):'<p>ยังไม่มีออเดอร์</p>'; }
async function load(){try{dashboard=await api('/api/admin/dashboard',{headers:{'X-Admin-Key':$('#key').value}});render();}catch(error){alert(error.message);}}
$('#load').onclick=load;
$('#settings-form').onsubmit=async event=>{event.preventDefault();try{await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});await load();}catch(error){alert(error.message);}};
$('#menu-form').onsubmit=async event=>{event.preventDefault();try{await api('/api/admin/menu',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});event.currentTarget.reset();await load();}catch(error){alert(error.message);}};
$('#menu-list').onclick=async event=>{const button=event.target.closest('[data-menu]');if(!button)return;try{await api(`/api/admin/menu/${button.dataset.menu}`,{method:'PATCH',body:JSON.stringify({available:button.dataset.available==='true'})});await load();}catch(error){alert(error.message);}};
$('#orders').onchange=async event=>{const select=event.target;if(!select.dataset.order)return;try{await api(`/api/admin/orders/${select.dataset.order}`,{method:'PATCH',body:JSON.stringify({[select.dataset.field]:select.value})});await load();}catch(error){alert(error.message);}};
