const $ = selector => document.querySelector(selector);
const money = n => `฿${Number(n).toLocaleString('th-TH')}`;
const safe = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
let dashboard;
function message(text, error=false) { const node=$('#notice'); node.textContent=text; node.className=`notice ${error?'error':''}`; }
function encodedHeader(value){return btoa(Array.from(new TextEncoder().encode(value),byte=>String.fromCharCode(byte)).join(''));}
async function api(url, options={}) {
  const response=await fetch(url,{...options,headers:{'Content-Type':'application/json','X-Admin-Key-B64':encodedHeader($('#key').value),...(options.headers||{})}});
  const raw=await response.text(); let data={}; try { data=raw?JSON.parse(raw):{}; } catch { throw new Error('เซิร์ฟเวอร์ส่งข้อมูลไม่สมบูรณ์ กรุณาลองใหม่'); }
  if(!response.ok) throw new Error(data.error||`เกิดข้อผิดพลาด (${response.status})`); return data;
}
const orderCard=order=>`<article class="menu-item"><div><h4>${safe(order.id)} · ${safe(order.customer.name)}</h4><p>${safe(order.customer.phone)} · ${safe(order.pickup.date)} ${safe(order.pickup.slot)}</p><p>${order.items.map(item=>`${safe(item.name)} × ${Number(item.quantity)}`).join(', ')} · ชำระ: ${safe(order.payment.status)}</p><p class="price">${money(order.total)}</p></div><div class="order-actions"><select data-order="${safe(order.id)}" data-field="status">${['new','confirmed','ready','completed','cancelled'].map(value=>`<option value="${value}" ${value===order.status?'selected':''}>${value}</option>`).join('')}</select><select data-order="${safe(order.id)}" data-field="payment_status">${['pending','paid','refunded'].map(value=>`<option value="${value}" ${value===order.payment.status?'selected':''}>${value}</option>`).join('')}</div></article>`;
function render() {
  const {summary,orders,settings,payments=[],audit=[]}=dashboard; $('#dashboard').hidden=false;
  $('#summary').innerHTML=`<div><strong>${Number(summary.orders)}</strong><span>ออเดอร์ทั้งหมด</span></div><div><strong>${Number(summary.active_orders)}</strong><span>กำลังดำเนินการ</span></div><div><strong>${money(summary.revenue)}</strong><span>ยอดจอง</span></div><div><strong>${Number(summary.ready)}</strong><span>พร้อมรับ</span></div>`;
  $('#slot-capacity').value=settings.slot_capacity; $('#advance-days').value=settings.advance_days;
  $('#menu-list').innerHTML=settings.menu.map(item=>`<article class="menu-item"><div><h4>${safe(item.name)} ${item.available?'':'(ปิดขาย)'}</h4><p>${safe(item.description)}</p><p class="price">${money(item.price)}</p></div><button class="text-button" data-menu="${safe(item.id)}" data-available="${Boolean(!item.available)}">${item.available?'ปิดขาย':'เปิดขาย'}</button></article>`).join('');
  $('#orders').innerHTML=orders.length?orders.map(orderCard).join(''):'<p>ยังไม่มีออเดอร์</p>';
  $('#payments').innerHTML=payments.length?payments.map(payment=>`<article class="menu-item"><div><h4>${safe(payment.id)} · ${safe(payment.status)}</h4><p>${safe(payment.provider_order_id||'รอ SCB order ID')} · ${money(payment.amount)}</p><p><small>${safe(new Date(payment.created_at).toLocaleString('th-TH'))}</small></p></div>${payment.status==='pending'?`<button class="text-button" data-payment="${safe(payment.id)}">ตรวจสอบกับ SCB</button>`:''}</article>`).join(''):'<p>ยังไม่มี SCB QR payment</p>';
  $('#audit').innerHTML=audit.length?audit.map(item=>`<p><b>${safe(item.actor_role)}</b> · ${safe(item.action)} ${safe(item.entity_type)} <code>${safe(item.entity_id)}</code><small>${safe(new Date(item.at).toLocaleString('th-TH'))}</small></p>`).join(''):'<p>ยังไม่มีกิจกรรม</p>';
}
async function load(){try{dashboard=await api('/api/admin/dashboard');render();message('อัปเดตข้อมูลแล้ว');}catch(error){message(error.message,true);}}
$('#load').onclick=load;
async function checkScbStatus(){const data=await api('/api/admin/scb/auth/status');$('#scb-auth-status').textContent=data.connected?`เชื่อมต่อแล้ว · access token หมดอายุ ${new Date(data.access_expires_at).toLocaleString('th-TH')}`:'ยังไม่ได้เชื่อมต่อ SCB EASY — เปิดขั้นตอนที่ 2 ใน SCB EASY Simulator แล้วอนุมัติคำขอ';return data;}
$('#scb-connect').onclick=async()=>{try{const data=await api('/api/admin/scb/auth/start');const link=$('#scb-auth-link');const scheme=new URL(data.authorization_url).protocol;if(scheme!=='scbeasysim:'&&scheme!=='scbeasy:')throw new Error('SCB ส่ง authorization link ที่ไม่รองรับ');link.href=data.authorization_url;link.hidden=false;$('#scb-auth-status').textContent='สร้างคำขอแล้ว: เปิดขั้นตอนที่ 2 บนอุปกรณ์ที่ติดตั้ง SCB EASY Simulator เท่านั้น แล้วอนุมัติคำขอทันที';}catch(error){message(error.message,true);}};
$('#scb-auth-link').onclick=()=>{$('#scb-auth-status').textContent='กำลังเปิด SCB EASY Simulator… หลังอนุมัติ ให้กลับมาหน้านี้ ระบบจะตรวจสอบสถานะให้อัตโนมัติ';};
$('#scb-status').onclick=async()=>{try{await checkScbStatus();}catch(error){message(error.message,true);}};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&$('#dashboard').hidden===false)checkScbStatus().catch(()=>{});});
$('#settings-form').onsubmit=async event=>{event.preventDefault();try{await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});await load();}catch(error){message(error.message,true);}};
$('#menu-form').onsubmit=async event=>{event.preventDefault();try{await api('/api/admin/menu',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});event.currentTarget.reset();await load();}catch(error){message(error.message,true);}};
$('#menu-list').onclick=async event=>{const button=event.target.closest('[data-menu]');if(!button)return;try{await api(`/api/admin/menu/${button.dataset.menu}`,{method:'PATCH',body:JSON.stringify({available:button.dataset.available==='true'})});await load();}catch(error){message(error.message,true);}};
$('#orders').onchange=async event=>{const select=event.target;if(!select.dataset.order)return;try{await api(`/api/admin/orders/${select.dataset.order}`,{method:'PATCH',body:JSON.stringify({[select.dataset.field]:select.value})});await load();}catch(error){message(error.message,true);}};
$('#payments').onclick=async event=>{const button=event.target.closest('[data-payment]');if(!button)return;button.disabled=true;try{const data=await api(`/api/admin/payments/scb/${button.dataset.payment}/inquire`,{method:'POST',body:'{}'});message(data.inquiry==='paid'?'SCB ยืนยันยอดชำระแล้ว':'SCB ยังไม่ยืนยันยอดชำระ');await load();}catch(error){message(error.message,true);button.disabled=false;}};
