const state = { menu: [], quantities: {}, slots: [] };
const money = value => `฿${value.toLocaleString("th-TH")}`;
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"})[char]);
async function responseData(response) { const text = await response.text(); try { return text ? JSON.parse(text) : { error: `เซิร์ฟเวอร์ตอบกลับว่างเปล่า (HTTP ${response.status})` }; } catch { return { error: `เซิร์ฟเวอร์ตอบกลับไม่ถูกต้อง (HTTP ${response.status})` }; } }

function total() { return state.menu.reduce((sum, item) => sum + item.price * (state.quantities[item.id] || 0), 0); }
function renderMenu() { document.querySelector("#menu").innerHTML = state.menu.map(item => { const quantity = state.quantities[item.id] || 0; return `<article class="menu-item"><div><h4>${escapeHtml(item.name)}</h4><p>${escapeHtml(item.description)}</p><p class="price">${money(item.price)}</p></div><div class="quantity"><button type="button" data-id="${item.id}" data-change="-1" aria-label="ลดจำนวน">−</button><output>${quantity}</output><button type="button" data-id="${item.id}" data-change="1" aria-label="เพิ่มจำนวน">+</button></div></article>`; }).join(""); document.querySelector("#total").textContent = money(total()); }
function renderSlots() { const select = document.querySelector("#pickup-slot"); select.innerHTML = `<option value="">เลือกรอบ</option>${state.slots.map(slot => `<option value="${slot.time}" ${slot.available ? "" : "disabled"}>${slot.time} ${slot.available ? `(เหลือ ${slot.remaining})` : "เต็ม"}</option>`).join("")}`; }
async function loadMenu() { const day = document.querySelector("#pickup-date").value; const response = await fetch(`/api/menu?date=${encodeURIComponent(day)}`); const data = await responseData(response); if (!response.ok) throw new Error(data.error || "ไม่สามารถโหลดเมนูได้"); state.menu = data.items; state.slots = data.slots; document.querySelector(".brand").firstChild.textContent = data.store_name; renderMenu(); renderSlots(); }
async function loadPaymentOptions() { const response = await fetch("/api/payments/scb/config"); const data = await responseData(response); if (!response.ok || !data.enabled) return; const select = document.querySelector("select[name=payment_method]"); if (!select.querySelector("option[value=scb_qr]")) select.insertAdjacentHTML("beforeend", '<option value="scb_qr">สแกนจ่าย PromptPay / SCB QR</option>'); }
async function setup() { const input = document.querySelector("#pickup-date"); const today = new Date(); today.setDate(today.getDate() + 1); input.min = today.toISOString().slice(0, 10); input.value = input.min; input.addEventListener("change", () => loadMenu().catch(error => alert(error.message))); await Promise.all([loadMenu(), loadPaymentOptions()]); }
document.querySelector("#menu").addEventListener("click", event => { const button = event.target.closest("button[data-id]"); if (!button) return; const id = button.dataset.id; state.quantities[id] = Math.max(0, (state.quantities[id] || 0) + Number(button.dataset.change)); renderMenu(); });
document.querySelector("#order-form").addEventListener("submit", async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form); payload.items = Object.entries(state.quantities).filter(([, quantity]) => quantity > 0).map(([id, quantity]) => ({ id, quantity })); const submit = event.currentTarget.querySelector("button[type=submit]"); submit.disabled = true; submit.textContent = "กำลังบันทึก…"; try { const response = await fetch("/api/orders", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(payload) }); const data = await responseData(response); if (!response.ok) throw new Error(data.error || "ไม่สามารถบันทึกออเดอร์ได้"); const confirmation = data.order.status === "confirmed" ? "ออเดอร์ยืนยันอัตโนมัติแล้ว" : "รับออเดอร์แล้ว รอยืนยันจากร้าน"; let qr = ""; if (data.order.payment.method === "scb_qr") { const qrResponse = await fetch(`/api/orders/${encodeURIComponent(data.order.id)}/payments/scb/qr`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone:payload.phone})}); const qrData = await responseData(qrResponse); if (!qrResponse.ok) throw new Error(qrData.error || "ไม่สามารถสร้าง SCB QR ได้"); const encoded = String(qrData.payment.qr_image || "").replace(/\s/g, ""); if (!/^[A-Za-z0-9+/=]+$/.test(encoded)) throw new Error("SCB QR ไม่ถูกต้อง"); qr = `<br><strong>สแกนเพื่อชำระเงิน</strong><br><img class="payment-qr" src="data:image/gif;base64,${encoded}" alt="SCB PromptPay QR สำหรับออเดอร์ ${escapeHtml(data.order.id)}"><br><small>ระบบจะอัปเดตสถานะเมื่อธนาคารยืนยันรายการ</small>`; } document.querySelector("#confirmation").innerHTML = `<strong>${confirmation}</strong><br>เลขที่ออเดอร์ <strong>${data.order.id}</strong><br>รับวันที่ ${data.order.pickup.date} รอบ ${data.order.pickup.slot}<br>ยอดรวม ${money(data.order.total)}${qr || "<br><small>สถานะชำระเงินจะอัปเดตหลังตรวจสอบยอด</small>"}`; document.querySelector("#success").showModal(); event.currentTarget.reset(); state.quantities = {}; await loadMenu(); } catch (error) { alert(error.message || "ไม่สามารถบันทึกออเดอร์ได้"); } finally { submit.disabled = false; submit.textContent = "ยืนยันการสั่งล่วงหน้า"; } });
document.querySelector("#lookup-form").addEventListener("submit", async event => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); const result = document.querySelector("#lookup-result"); try { const response = await fetch("/api/order-lookup", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const data = await responseData(response); if (!response.ok) throw new Error(data.error || "ไม่พบออเดอร์"); const order = data.order; result.hidden=false; result.innerHTML=`<h3>${order.id}</h3><p>สถานะ: <strong>${order.status}</strong> · ${order.pickup.date} ${order.pickup.slot}</p><p>${order.items.map(item=>`${escapeHtml(item.name)} × ${item.quantity}`).join(" · ")} · <strong>${money(order.total)}</strong></p>${data.can_cancel ? '<button class="text-button" id="cancel-order">ยกเลิกออเดอร์นี้</button>' : ''}`; const cancel = document.querySelector("#cancel-order"); if(cancel) cancel.onclick=async()=>{if(!confirm("ยืนยันการยกเลิกออเดอร์?"))return;const response=await fetch(`/api/orders/${order.id}/cancel`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone:form.phone})});const next=await responseData(response);if(!response.ok)return alert(next.error || "ยกเลิกไม่สำเร็จ");result.querySelector("strong").textContent="cancelled";cancel.remove();await loadMenu();}; } catch (error) { result.hidden=false; result.textContent=error.message; } });
document.querySelectorAll(".close").forEach(button => button.addEventListener("click", () => document.querySelector("#success").close()));
setup().catch(error => alert(error.message || "ไม่สามารถโหลดเมนูได้ กรุณาลองใหม่"));
