const el = id => document.querySelector(`#${id}`);
const money = value => `฿${Number(value).toLocaleString("th-TH")}`;
const safe = value => String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"})[char]);
function headers() { return {"Content-Type":"application/json","X-Admin-Key-B64":btoa(unescape(encodeURIComponent(el("key").value)))}; }
async function api(url, method = "GET", body) { const response = await fetch(url, {method, headers:headers(), body:body ? JSON.stringify(body) : undefined}); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "ดำเนินการไม่สำเร็จ"); return data; }
function formData(form) { return Object.fromEntries(new FormData(form)); }
function options(rows, value, label) { return `<option value="">เลือก</option>${rows.map(row => `<option value="${safe(row[value])}">${safe(row[label])}</option>`).join("")}`; }

async function load() {
  try {
    const data = await api("/api/admin/operations");
    el("workspace").hidden = false; el("notice").textContent = "";
    Object.entries(data.business_profile).forEach(([key, value]) => { const input = el("business-form").elements[key]; if (input) input.type === "checkbox" ? input.checked = Boolean(value) : input.value = value; });
    Object.entries(data.delivery_pricing).forEach(([key, value]) => { const input = el("pricing-form").elements[key]; if (input && value !== null) input.value = value; });
    el("merchant-applications").innerHTML = data.merchant_applications.map(item => `<article class="menu-item"><div><strong>${safe(item.business_name)}</strong><p>${safe(item.owner_name)} · ${safe(item.phone)} · ${safe(item.category)} · ${safe(item.status)}</p><p>${safe(item.address)}</p></div><div>${item.status === "pending" ? `<button class="text-button" data-merchant-application="${safe(item.id)}" data-decision="approved">อนุมัติ</button><button class="text-button" data-merchant-application="${safe(item.id)}" data-decision="rejected">ปฏิเสธ</button>` : ""}</div></article>`).join("") || "<p>ยังไม่มีใบสมัครร้านค้า</p>";
    el("zones").innerHTML = data.delivery_zones.map(zone => `<p><strong>${safe(zone.name)}</strong> · ค่าส่ง ${money(zone.fee)} · ขั้นต่ำ ${money(zone.minimum_order)}</p>`).join("");
    el("rider-applications").innerHTML = data.rider_applications.map(item => `<article class="menu-item"><div><strong>${safe(item.name)}</strong><p>${safe(item.phone)} · ${safe(item.vehicle_type)} ${safe(item.vehicle_plate)} · ${safe(item.status)}</p></div><div>${item.status === "pending" ? `<button class="text-button" data-application="${safe(item.id)}" data-decision="approved">อนุมัติ</button><button class="text-button" data-application="${safe(item.id)}" data-decision="rejected">ปฏิเสธ</button>` : ""}</div></article>`).join("") || "<p>ยังไม่มีใบสมัคร</p>";
    el("riders").innerHTML = data.riders.map(item => `<article class="menu-item"><div><strong>${safe(item.name)}</strong><p>${safe(item.phone)} · ${item.active ? (item.available ? "พร้อมรับงาน" : "พักงาน") : "ปิดใช้งาน"}</p></div><div><button class="text-button" data-rider-id="${safe(item.id)}" data-available="${item.available ? "false" : "true"}">${item.available ? "พักงาน" : "พร้อมรับงาน"}</button></div></article>`).join("") || "<p>ยังไม่มีไรเดอร์</p>";
    el("recipe-menu").innerHTML = options(data.menu, "id", "name");
    el("recipe-inventory").innerHTML = options(data.inventory, "id", "name");
    el("deliveries").innerHTML = data.deliveries.map(item => `<article class="menu-item"><div><strong>${safe(item.order_id)}</strong><p>${safe(item.recipient_name)} · ${safe(item.address)}</p><p>${safe(item.zone_name)} · ${safe(item.status)} · ${safe(item.rider_name || "ยังไม่มอบหมาย")}</p></div><div>${data.riders.map(rider => `<button class="text-button" data-delivery="${safe(item.order_id)}" data-rider="${safe(rider.id)}">${safe(rider.name)}</button>`).join(" ")}<button class="text-button" data-delivery="${safe(item.order_id)}" data-status="picked_up">รับแล้ว</button><button class="text-button" data-delivery="${safe(item.order_id)}" data-status="on_the_way">กำลังส่ง</button><button class="text-button" data-delivery="${safe(item.order_id)}" data-status="delivered">ส่งสำเร็จ</button><button class="text-button" data-receipt="${safe(item.order_id)}">ออกใบเสร็จ</button></div></article>`).join("") || "<p>ยังไม่มีงานจัดส่ง</p>";
    el("inventory").innerHTML = data.inventory.map(item => `<article class="menu-item"><div><strong>${safe(item.name)}</strong><p>${Number(item.on_hand)} ${safe(item.unit)} · เตือนเมื่อ ${Number(item.reorder_level)}</p></div><div><button class="text-button" data-stock="${safe(item.id)}" data-delta="1">+1</button><button class="text-button" data-stock="${safe(item.id)}" data-delta="-1">-1</button></div></article>`).join("") || "<p>ยังไม่มีวัตถุดิบ</p>";
    el("recipes").innerHTML = data.recipes.map(recipe => `<p>${safe(recipe.menu_name)}: ${recipe.quantity} ${safe(recipe.unit)} ของ ${safe(recipe.inventory_name)}</p>`).join("") || "<p>ยังไม่มีสูตรตัดสต็อก</p>";
    el("coupons").innerHTML = data.coupons.map(item => `<article class="menu-item"><div><strong>${safe(item.code)}</strong><p>${item.kind === "percent" ? item.value + "%" : money(item.value)} · ขั้นต่ำ ${money(item.minimum_order)} · ใช้แล้ว ${item.used_count}${item.maximum_uses ? "/" + item.maximum_uses : ""}</p></div></article>`).join("") || "<p>ยังไม่มีคูปอง</p>";
    const invoices = new Map(data.tax_invoices.map(item => [item.receipt_id, item]));
    el("receipts").innerHTML = data.receipts.map(item => { const invoice = invoices.get(item.id); return `<article class="menu-item"><div><strong>${safe(item.receipt_number)}</strong><p>${safe(item.order_id)} · ${money(item.total)}${invoice ? ` · ภาษี ${safe(invoice.tax_invoice_number)}` : ""}</p></div><div><button class="text-button" data-print="${safe(item.id)}">พิมพ์</button>${invoice ? "" : `<button class="text-button" data-invoice="${safe(item.id)}">ออกใบกำกับภาษี</button>`}</div></article>`; }).join("") || "<p>ยังไม่มีใบเสร็จ</p>";
  } catch (error) { el("notice").textContent = error.message; }
}

el("load").onclick = load;
[["rider", "/api/admin/riders"], ["zone", "/api/admin/delivery-zones"], ["inventory", "/api/admin/inventory"], ["recipe", "/api/admin/inventory/recipes"], ["coupon", "/api/admin/coupons"]].forEach(([name, url]) => el(`${name}-form`).addEventListener("submit", async event => { event.preventDefault(); try { await api(url, "POST", formData(event.currentTarget)); event.currentTarget.reset(); load(); } catch (error) { alert(error.message); } }));
el("business-form").addEventListener("submit", async event => { event.preventDefault(); try { const form = formData(event.currentTarget); form.vat_registered = event.currentTarget.elements.vat_registered.checked; await api("/api/admin/business-profile", "POST", form); load(); } catch (error) { alert(error.message); } });
el("merchant-applications").onclick = async event => { const button = event.target.closest("button[data-merchant-application]"); if (!button) return; try { await api(`/api/admin/merchant-applications/${button.dataset.merchantApplication}`, "PATCH", {status:button.dataset.decision}); load(); } catch (error) { alert(error.message); } };
el("rider-applications").onclick = async event => { const button = event.target.closest("button[data-application]"); if (!button) return; try { await api(`/api/admin/rider-applications/${button.dataset.application}`, "PATCH", {status:button.dataset.decision}); load(); } catch (error) { alert(error.message); } };
el("riders").onclick = async event => { const button = event.target.closest("button[data-rider-id]"); if (!button) return; try { await api(`/api/admin/riders/${button.dataset.riderId}`, "PATCH", {available:button.dataset.available === "true"}); load(); } catch (error) { alert(error.message); } };
el("pricing-form").addEventListener("submit", async event => { event.preventDefault(); try { await api("/api/admin/delivery-pricing", "POST", formData(event.currentTarget)); load(); } catch (error) { alert(error.message); } });
el("store-location-button").addEventListener("click", () => { if (!navigator.geolocation) return alert("เบราว์เซอร์นี้ไม่รองรับตำแหน่ง"); navigator.geolocation.getCurrentPosition(position => { el("store-latitude").value = position.coords.latitude; el("store-longitude").value = position.coords.longitude; }, () => alert("ไม่สามารถอ่านตำแหน่งได้"), {enableHighAccuracy:true, timeout:10000}); });
el("deliveries").onclick = async event => { const button = event.target.closest("button"); if (!button) return; try { if (button.dataset.receipt) await api(`/api/admin/orders/${button.dataset.receipt}/receipt`, "POST", {}); else await api(`/api/admin/deliveries/${button.dataset.delivery}`, "PATCH", button.dataset.rider ? {rider_id:button.dataset.rider} : {status:button.dataset.status}); load(); } catch (error) { alert(error.message); } };
el("inventory").onclick = async event => { const button = event.target.closest("button[data-stock]"); if (!button) return; try { await api("/api/admin/inventory/adjust", "POST", {inventory_item_id:button.dataset.stock, delta:Number(button.dataset.delta), reason:"owner_adjustment"}); load(); } catch (error) { alert(error.message); } };
el("receipts").onclick = async event => { const button = event.target.closest("button"); if (!button) return; try { if (button.dataset.invoice) { const buyer_name = prompt("ชื่อผู้ซื้อสำหรับใบกำกับภาษี"); if (!buyer_name) return; await api(`/api/admin/receipts/${button.dataset.invoice}/tax-invoice`, "POST", {buyer_name, buyer_tax_id:prompt("เลขผู้เสียภาษีผู้ซื้อ (ถ้ามี)") || "", buyer_address:prompt("ที่อยู่ผู้ซื้อ (ถ้ามี)") || ""}); load(); } if (button.dataset.print) { const response = await fetch(`/api/admin/receipts/${button.dataset.print}/print`, {headers:headers()}); if (!response.ok) throw new Error("เปิดเอกสารไม่ได้"); const win = window.open("", "_blank"); if (!win) throw new Error("เบราว์เซอร์บล็อกหน้าต่างพิมพ์"); win.document.write(await response.text()); win.document.close(); } } catch (error) { alert(error.message); } };
